# Generated by Django 5.1.3 on 2024-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(help_text='Указывайте цену в сомах')),
                ('image', models.ImageField(upload_to='pizza_images/')),
                ('consist', models.TextField(verbose_name='Состав')),
                ('is_new', models.BooleanField()),
                ('size', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес в граммах')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
    ]
