# Generated by Django 5.1.3 on 2024-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название напитка')),
                ('price', models.PositiveIntegerField(help_text='Указывайте цену в сомах')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Объем в мл')),
                ('image', models.ImageField(upload_to='drink_images/', verbose_name='Изображение')),
                ('is_cold', models.BooleanField(default=True, verbose_name='Охлажденный')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
    ]
