# Generated by Django 5.1.3 on 2024-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.PositiveSmallIntegerField(verbose_name='Объем в л'),
        ),
    ]
