# Generated by Django 5.1.3 on 2024-11-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_drink_volume'),
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPizzaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
